export const store = {
  referrers: [
    {
      id: 1,
      title: "Dr.",
      firstName: "Self",
      lastName: "",
      degree: "",
      mobile: "",
      email: "",
      address: "",
      active: true,
    },
  ],
  agents: [{ id: 1, name: "Main Collection Agent", active: true }],
  bills: [
    {
      id: 1,
      regNo: "41025",
      caseNo: "L82",
      patient: "Demo Patient",
      mobile: "9000000000",
      referrer: "Dr. Self",
      total: 850,
      discount: 50,
      received: 800,
      balance: 0,
      mode: "cash",
      status: "Active",
      createdAt: "2026-09-23T09:49:00",
      investigations: [
        { name: "Complete Blood Count (CBC)", price: 350, type: "lab" },
        { name: "Liver Function Test (LFT)", price: 500, type: "lab" },
      ],
    },
  ],
  reports: [
    {
      id: 1,
      billId: 1,
      regNo: "41025",
      patient: "Demo Patient",
      age: "26 YRS/M",
      referrer: "Dr. Self",
      status: "New",
      tests: [
        {
          id: 1,
          section: "HAEMATOLOGY",
          name: "Hemoglobin",
          value: "",
          unit: "g/dL",
          reference: "13.0 - 17.0",
        },
        {
          id: 2,
          section: "HAEMATOLOGY",
          name: "Total Leukocyte Count",
          value: "",
          unit: "/cumm",
          reference: "4000 - 11000",
        },
        {
          id: 3,
          section: "BIOCHEMISTRY",
          name: "Bilirubin Total",
          value: "",
          unit: "mg/dL",
          reference: "0.3 - 1.2",
        },
      ],
      interpretation: "",
      notes: "",
    },
  ],
  employees: [
    {
      id: 1,
      firstName: "Demo",
      lastName: "Owner",
      email: "owner@example.com",
      mobile: "9000000001",
      active: true,
      owner: true,
      permissions: ["all"],
    },
    {
      id: 2,
      firstName: "Demo",
      lastName: "Technician",
      email: "technician@example.com",
      mobile: "9000000002",
      active: true,
      owner: false,
      permissions: ["billing.view", "lab.view", "lab.edit"],
    },
  ],
};
export const nextId = (rows) =>
  Math.max(0, ...rows.map((x) => Number(x.id) || 0)) + 1;
